# -*- coding: utf-8 -*-
"""Maria_Kausar_YOLOv9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6Rgnn063YIT9ssCc_sU7TirwdK7gcUh
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/SkalskiP/yolov9.git
# %cd yolov9
!pip install -r requirements.txt -q

!pip install -q roboflow pyyaml

!wget -P {HOME}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/yolov9-c.pt
!wget -P {HOME}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/yolov9-e.pt
!wget -P {HOME}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/gelan-c.pt
!wget -P {HOME}/weights -q https://github.com/WongKinYiu/yolov9/releases/download/v0.1/gelan-e.pt

!ls -la {HOME}/weights

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov9

from roboflow import Roboflow
rf = Roboflow(api_key="bzkcK5It5sCeCviXjqrY")
project = rf.workspace("maria-4iqc2").project("object-detection-bus-dataset")
version = project.version(2)
dataset = version.download("yolov9")

dataset.location

import yaml

# Step 1: Read the YAML file
input_file = f"{dataset.location}/data.yaml"
with open(input_file, 'r') as file:
    data = yaml.safe_load(file)
    print(data)

# Step 2: Add static paths
data["test"] = f"{dataset.location}/test/images"
data["train"] = f"{dataset.location}/train/images"
data["val"] = f"{dataset.location}/valid/images"

# Step 3.3: Write the updated content back to a YAML file
output_file = f"{dataset.location}/data-updated.yaml"
with open(output_file, 'w') as file:
    yaml.dump(data, file, default_flow_style=False)

print(f"Updated YAML saved to {output_file}")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov9

!python train.py \
--batch 16 --epochs 50 --img 294 --device 0 --min-items 0 --close-mosaic 15 \
--data {dataset.location}/data-updated.yaml \
--weights {HOME}/weights/gelan-c.pt \
--cfg models/detect/gelan-c.yaml \
--hyp hyp.scratch-high.yaml

!ls {HOME}/yolov9/runs/train/exp/

from IPython.display import Image

Image(filename=f"{HOME}/yolov9/runs/train/exp/results.png", width=1000)

from IPython.display import Image

Image(filename=f"{HOME}/yolov9/runs/train/exp/confusion_matrix.png", width=1000)

from IPython.display import Image

try:
  Image(filename=f"{HOME}/yolov9/runs/train/exp/val_batch0_pred.jpg", width=1000)
except:
  print("No images found")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}/yolov9

!python val.py \
--img 294 --batch 32 --conf 0.001 --iou 0.7 --device 0 \
--data {dataset.location}/data-updated.yaml \
--weights {HOME}/yolov9/runs/train/exp/weights/best.pt

!python detect.py \
--img 1280 --conf 0.1 --device 0 \
--weights {HOME}/yolov9/runs/train/exp/weights/best.pt \
--source {dataset.location}/test/images

import glob

from IPython.display import Image, display

for image_path in glob.glob(f'{HOME}/yolov9/runs/detect/exp/*.jpg')[:2]:
      display(Image(filename=image_path, width=600))

